import type { ModelInfo } from "../model.js"

// Azure AI models deployed via Azure AI Foundry and Azure OpenAI
export type AzureModelId = keyof typeof azureModels

export const azureDefaultModelId: AzureModelId = "claude-sonnet-4-5"

export const azureModels = {
	"claude-sonnet-4-5": {
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningBudget: true,
		inputPrice: 3.0,
		outputPrice: 15.0,
		cacheWritesPrice: 3.75,
		cacheReadsPrice: 0.3,
		supportsTemperature: true,
		description: "Claude Sonnet 4.5 on Azure AI Foundry - Extended thinking and vision capabilities",
	},
	"gpt-5-pro": {
		maxTokens: 128_000,
		contextWindow: 400_000,
		supportsNativeTools: true,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["high"],
		reasoningEffort: "high",
		inputPrice: 1.25,
		outputPrice: 10.0,
		cacheReadsPrice: 0.125,
		supportsTemperature: true,
		description: "GPT-5-Pro on Azure OpenAI - Most powerful for complex tasks with high reasoning effort",
	},
	"gpt-5.1": {
		maxTokens: 128_000,
		contextWindow: 400_000,
		supportsNativeTools: true,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["none", "low", "medium", "high"],
		reasoningEffort: "medium",
		inputPrice: 1.25,
		outputPrice: 10.0,
		cacheReadsPrice: 0.125,
		supportsVerbosity: true,
		supportsTemperature: false,
		description: "GPT-5.1 on Azure OpenAI - Adaptive reasoning with flexible effort levels",
	},
	"claude-haiku-4-5": {
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningBudget: true,
		inputPrice: 0.6,
		outputPrice: 3.0,
		cacheWritesPrice: 0.75,
		cacheReadsPrice: 0.06,
		supportsTemperature: true,
		description: "Claude Haiku 4.5 on Azure AI Foundry - Fast and efficient for everyday tasks",
	},
	"claude-opus-4-1": {
		maxTokens: 64_000,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningBudget: true,
		inputPrice: 15.0,
		outputPrice: 75.0,
		cacheWritesPrice: 18.75,
		cacheReadsPrice: 1.5,
		supportsTemperature: true,
		description: "Claude Opus 4.1 on Azure AI Foundry - Most powerful Claude model for complex reasoning",
	},
	"gpt-5-chat": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsNativeTools: true,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 1.0,
		outputPrice: 5.0,
		supportsTemperature: true,
		description: "GPT-5-Chat on Azure OpenAI - Optimized for conversational tasks",
	},
	"gpt-5-mini": {
		maxTokens: 16_384,
		contextWindow: 400_000,
		supportsNativeTools: true,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.5,
		outputPrice: 2.5,
		supportsTemperature: false,
		description: "GPT-5-Mini on Azure OpenAI - Compact and efficient for simple tasks",
	},
	"gpt-5-nano": {
		maxTokens: 16_384,
		contextWindow: 400_000,
		supportsNativeTools: true,
		supportsImages: true,
		supportsPromptCache: false,
		inputPrice: 0.25,
		outputPrice: 1.25,
		supportsTemperature: false,
		description: "GPT-5-Nano on Azure OpenAI - Ultra-compact and cost-effective",
	},
	"gpt-5-codex": {
		maxTokens: 128_000,
		contextWindow: 400_000,
		supportsNativeTools: true,
		supportsImages: false,
		supportsPromptCache: true,
		inputPrice: 1.5,
		outputPrice: 8.0,
		cacheReadsPrice: 0.15,
		supportsTemperature: true,
		description: "GPT-5-Codex on Azure OpenAI - Specialized for code generation and analysis",
	},
	"gpt-5.1-codex": {
		maxTokens: 128_000,
		contextWindow: 400_000,
		supportsNativeTools: true,
		supportsImages: false,
		supportsPromptCache: true,
		supportsReasoningEffort: ["none", "low", "medium", "high"],
		reasoningEffort: "medium",
		inputPrice: 1.5,
		outputPrice: 8.0,
		cacheReadsPrice: 0.15,
		supportsVerbosity: true,
		supportsTemperature: false,
		description: "GPT-5.1-Codex on Azure OpenAI - Advanced code model with adaptive reasoning",
	},
} as const satisfies Record<string, ModelInfo>
