import { ProviderMetadataMap } from "./provider-metadata.js"

/**
 * Comprehensive provider metadata with categorization
 */
export const PROVIDER_METADATA: ProviderMetadataMap = {
	// Premium Cloud Providers (Paid, High Quality)
	"openai-native": {
		id: "openai-native",
		label: "OpenAI",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "premium",
		authentication: "api-key",
		recommended: true,
		deprecated: false,
		description: "Official OpenAI API with GPT-4, GPT-4 Turbo, and GPT-5 models",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
			supportsPromptCaching: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		costInfo: {
			pricingUrl: "https://openai.com/pricing",
		},
		tags: ["official", "gpt", "premium"],
	},
	anthropic: {
		id: "anthropic",
		label: "Anthropic",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "premium",
		authentication: "api-key",
		recommended: true,
		deprecated: false,
		description: "Claude models with strong reasoning and coding capabilities",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
			supportsPromptCaching: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
			contextWindow: 200000,
		},
		costInfo: {
			pricingUrl: "https://www.anthropic.com/pricing",
		},
		tags: ["official", "claude", "premium"],
	},
	gemini: {
		id: "gemini",
		label: "Google Gemini",
		category: "cloud",
		pricing: "freemium",
		quality: "premium",
		authentication: "api-key",
		recommended: true,
		deprecated: false,
		description: "Google's Gemini models with large context windows",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
			contextWindow: 1000000,
		},
		costInfo: {
			pricingUrl: "https://ai.google.dev/pricing",
			freeTokensPerMonth: 60,
		},
		tags: ["official", "google", "large-context"],
	},

	// Enterprise Cloud Providers
	bedrock: {
		id: "bedrock",
		label: "Amazon Bedrock",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "premium",
		authentication: "cloud-account",
		recommended: true,
		deprecated: false,
		description: "AWS managed service for various AI models",
		setupDifficulty: "advanced",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
			supportsPromptCaching: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		tags: ["enterprise", "aws", "multi-model"],
	},
	vertex: {
		id: "vertex",
		label: "GCP Vertex AI",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "premium",
		authentication: "cloud-account",
		recommended: true,
		deprecated: false,
		description: "Google Cloud's enterprise AI platform",
		setupDifficulty: "advanced",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		tags: ["enterprise", "gcp", "multi-model"],
	},

	// Local Providers (Free, Self-hosted)
	ollama: {
		id: "ollama",
		label: "Ollama",
		category: "local",
		pricing: "free",
		quality: "standard",
		authentication: "none",
		recommended: true,
		deprecated: false,
		description: "Run AI models locally on your machine",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "high",
		},
		tags: ["local", "open-source", "privacy"],
	},
	lmstudio: {
		id: "lmstudio",
		label: "LM Studio",
		category: "local",
		pricing: "free",
		quality: "standard",
		authentication: "none",
		recommended: true,
		deprecated: false,
		description: "User-friendly local model runner with GUI",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "high",
		},
		tags: ["local", "user-friendly", "privacy"],
	},

	// Router/Aggregator Services
	openrouter: {
		id: "openrouter",
		label: "OpenRouter",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: true,
		deprecated: false,
		description: "Access multiple AI providers through one API",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
			supportsPromptCaching: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		costInfo: {
			pricingUrl: "https://openrouter.ai/pricing",
		},
		tags: ["router", "multi-provider", "flexible"],
	},
	litellm: {
		id: "litellm",
		label: "LiteLLM",
		category: "hybrid",
		pricing: "freemium",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Unified interface for multiple LLM providers",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
		},
		performance: {
			speed: "medium",
			reliability: "medium",
		},
		tags: ["router", "proxy", "multi-provider"],
	},
	"vercel-ai-gateway": {
		id: "vercel-ai-gateway",
		label: "Vercel AI Gateway",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Vercel's unified AI gateway with caching",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		tags: ["router", "vercel", "caching"],
	},

	// Alternative/Specialized Providers
	deepseek: {
		id: "deepseek",
		label: "DeepSeek",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: true,
		deprecated: false,
		description: "Cost-effective Chinese AI provider with strong coding models",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		tags: ["affordable", "coding", "chinese"],
	},
	groq: {
		id: "groq",
		label: "Groq",
		category: "cloud",
		pricing: "freemium",
		quality: "standard",
		authentication: "api-key",
		recommended: true,
		deprecated: false,
		description: "Ultra-fast inference with specialized hardware",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		tags: ["fast", "free-tier", "specialized"],
	},
	cerebras: {
		id: "cerebras",
		label: "Cerebras",
		category: "cloud",
		pricing: "freemium",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Fast inference with Cerebras hardware",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "fast",
			reliability: "medium",
		},
		tags: ["fast", "specialized-hardware"],
	},
	mistral: {
		id: "mistral",
		label: "Mistral",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "European AI provider with efficient models",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		tags: ["european", "efficient"],
	},
	xai: {
		id: "xai",
		label: "xAI (Grok)",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Grok models from xAI",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: true,
		},
		performance: {
			speed: "fast",
			reliability: "medium",
		},
		tags: ["grok", "new"],
	},

	// Specialized/Niche Providers
	"claude-code": {
		id: "claude-code",
		label: "Claude Code",
		category: "cloud",
		pricing: "subscription",
		quality: "premium",
		authentication: "oauth",
		recommended: true,
		deprecated: false,
		description: "Claude optimized for coding tasks",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		tags: ["claude", "coding", "specialized"],
	},
	"qwen-code": {
		id: "qwen-code",
		label: "Qwen Code",
		category: "cloud",
		pricing: "free",
		quality: "standard",
		authentication: "oauth",
		recommended: false,
		deprecated: false,
		description: "Alibaba's Qwen model for coding",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: true,
		},
		performance: {
			speed: "medium",
			reliability: "medium",
		},
		tags: ["alibaba", "coding", "chinese"],
	},
	moonshot: {
		id: "moonshot",
		label: "Moonshot",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Chinese AI provider with large context models",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "medium",
		},
		tags: ["chinese", "large-context"],
	},
	doubao: {
		id: "doubao",
		label: "Doubao",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "ByteDance's AI models",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "medium",
		},
		tags: ["bytedance", "chinese"],
	},

	// Infrastructure/Development Providers
	deepinfra: {
		id: "deepinfra",
		label: "DeepInfra",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Serverless inference for open-source models",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "medium",
		},
		tags: ["open-source", "serverless"],
	},
	huggingface: {
		id: "huggingface",
		label: "Hugging Face",
		category: "cloud",
		pricing: "freemium",
		quality: "experimental",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Access thousands of open-source models",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "medium",
		},
		tags: ["open-source", "community", "experimental"],
	},
	sambanova: {
		id: "sambanova",
		label: "SambaNova",
		category: "cloud",
		pricing: "freemium",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Fast inference with SambaNova hardware",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "fast",
			reliability: "medium",
		},
		tags: ["specialized-hardware", "free-tier"],
	},
	fireworks: {
		id: "fireworks",
		label: "Fireworks AI",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Fast and affordable AI inference",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		tags: ["fast", "affordable"],
	},

	// Custom/Compatible Providers
	openai: {
		id: "openai",
		label: "OpenAI Compatible",
		category: "hybrid",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Connect to any OpenAI-compatible API endpoint",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "medium",
		},
		warning: "Compatibility varies by provider",
		tags: ["flexible", "custom", "compatible"],
	},

	// VSCode Integration
	"vscode-lm": {
		id: "vscode-lm",
		label: "VS Code LM API",
		category: "local",
		pricing: "free",
		quality: "standard",
		authentication: "none",
		recommended: false,
		deprecated: false,
		description: "Use models provided by VS Code extensions",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "high",
		},
		tags: ["vscode", "integrated", "copilot"],
	},

	// Lesser-known/Experimental Providers
	glama: {
		id: "glama",
		label: "Glama",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "experimental",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Multi-model AI gateway",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "medium",
		},
		tags: ["gateway", "experimental"],
	},
	unbound: {
		id: "unbound",
		label: "Unbound",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "experimental",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Experimental AI provider",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "low",
		},
		tags: ["experimental"],
	},
	requesty: {
		id: "requesty",
		label: "Requesty",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "experimental",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "API gateway service",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "low",
		},
		tags: ["gateway", "experimental"],
	},
	chutes: {
		id: "chutes",
		label: "Chutes AI",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "experimental",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Experimental AI provider",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "low",
		},
		tags: ["experimental"],
	},
	featherless: {
		id: "featherless",
		label: "Featherless AI",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "experimental",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Serverless AI inference",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "low",
		},
		tags: ["serverless", "experimental"],
	},
	"io-intelligence": {
		id: "io-intelligence",
		label: "IO Intelligence",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "experimental",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Experimental AI provider",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "low",
		},
		tags: ["experimental"],
	},
	zai: {
		id: "zai",
		label: "Z AI",
		category: "cloud",
		pricing: "pay-per-use",
		quality: "standard",
		authentication: "api-key",
		recommended: false,
		deprecated: false,
		description: "Zhipu AI models",
		setupDifficulty: "moderate",
		features: {
			supportsStreaming: true,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "medium",
			reliability: "medium",
		},
		tags: ["chinese", "zhipu"],
	},

	// Special/Internal Providers
	roo: {
		id: "roo",
		label: "Roo Code Cloud",
		category: "cloud",
		pricing: "subscription",
		quality: "premium",
		authentication: "cloud-account",
		recommended: true,
		deprecated: false,
		description: "Roo Code's managed cloud service",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: true,
			supportsImages: true,
			supportsTools: true,
			supportsPromptCaching: true,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		tags: ["official", "managed", "integrated"],
	},
	"human-relay": {
		id: "human-relay",
		label: "Human Relay",
		category: "local",
		pricing: "free",
		quality: "experimental",
		authentication: "none",
		recommended: false,
		deprecated: false,
		description: "Manual responses for testing",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: false,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "slow",
			reliability: "low",
		},
		warning: "For testing only - requires manual intervention",
		tags: ["testing", "manual", "development"],
	},
	"fake-ai": {
		id: "fake-ai",
		label: "Fake AI",
		category: "local",
		pricing: "free",
		quality: "experimental",
		authentication: "none",
		recommended: false,
		deprecated: false,
		description: "Mock AI for testing",
		setupDifficulty: "easy",
		features: {
			supportsStreaming: false,
			supportsImages: false,
			supportsTools: false,
		},
		performance: {
			speed: "fast",
			reliability: "high",
		},
		warning: "For testing only - returns mock responses",
		tags: ["testing", "mock", "development"],
	},
}
